import {
  Accessibility,
  Activity,
  AlarmClock,
  Ambulance,
  Anchor,
  Antenna,
  Apple,
  Armchair,
  AtSign,
  Axe,
  Baby,
  Backpack,
  BadgeCheck,
  Ban,
  Banana,
  Bandage,
  Banknote,
  Bath,
  Battery,
  BatteryCharging,
  Bean,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  Bell,
  Bike,
  Bird,
  Blinds,
  Blocks,
  Bluetooth,
  Bone,
  Book,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  BrushCleaning,
  Bug,
  Building,
  Building2,
  Bus,
  BusFront,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Candy,
  Car,
  CarFront,
  Caravan,
  Carrot,
  Castle,
  Cat,
  Cctv,
  Cherry,
  Church,
  CircleAlert,
  CircleHelp,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudSun,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  Cross,
  CupSoda,
  Dice5,
  Dna,
  Dog,
  DollarSign,
  DoorClosed,
  DoorOpen,
  Drama,
  Drill,
  Droplet,
  Droplets,
  Drumstick,
  Dumbbell,
  Ear,
  Egg,
  EggFried,
  Euro,
  Eye,
  EyeOff,
  Factory,
  Fan,
  Feather,
  Fence,
  File,
  FileCheck,
  FileLock,
  FileText,
  Files,
  Film,
  Fingerprint,
  FireExtinguisher,
  Fish,
  Flag,
  Flame,
  Flashlight,
  Flower,
  Flower2,
  Folder,
  FolderOpen,
  Footprints,
  Forklift,
  Frown,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  Globe2,
  GraduationCap,
  Grape,
  Guitar,
  Ham,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  Handshake,
  HardHat,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Hospital,
  Hotel,
  Hourglass,
  House,
  HousePlug,
  IceCreamCone,
  IdCard,
  Info,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  List,
  Lock,
  LockKeyhole,
  Luggage,
  Mail,
  MailOpen,
  Map,
  MapPin,
  MapPinned,
  Mars,
  Martini,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Music,
  Music2,
  Navigation,
  Newspaper,
  Notebook,
  NotebookPen,
  Nut,
  OctagonAlert,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pen,
  PenTool,
  Pencil,
  PersonStanding,
  Phone,
  PhoneCall,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  PlugZap,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  Rabbit,
  Radio,
  Receipt,
  Refrigerator,
  Route,
  Router,
  Rss,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  SatelliteDish,
  Scale,
  Scan,
  School,
  Scissors,
  Scroll,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Signal,
  Signature,
  Signpost,
  SignpostBig,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  Stamp,
  Star,
  Stethoscope,
  Sun,
  SunMedium,
  Syringe,
  Tablet,
  Tent,
  TentTree,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Timer,
  Toilet,
  Tractor,
  TrainFront,
  TramFront,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Umbrella,
  Unlock,
  Usb,
  User,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Venus,
  VenusAndMars,
  Video,
  Wallet,
  Warehouse,
  Watch,
  Waves,
  Wheat,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon vocabulary for catalogue services and categories, always paired with a
 * text label on public surfaces. Keys are the icon's own name in the Lucide
 * library (kebab-case) — the value stored on a row is exactly that name, so a
 * row's `icon` code is portable and unambiguous. Grouped by theme so the
 * picker reads sensibly top to bottom.
 */
const taxonomyIcons: Record<string, LucideIcon> = {
  // Food & drink
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  "cooking-pot": CookingPot,
  soup: Soup,
  sandwich: Sandwich,
  salad: Salad,
  apple: Apple,
  banana: Banana,
  carrot: Carrot,
  cherry: Cherry,
  grape: Grape,
  egg: Egg,
  "egg-fried": EggFried,
  beef: Beef,
  ham: Ham,
  fish: Fish,
  drumstick: Drumstick,
  croissant: Croissant,
  cake: Cake,
  "cake-slice": CakeSlice,
  "ice-cream-cone": IceCreamCone,
  cookie: Cookie,
  candy: Candy,
  popcorn: Popcorn,
  pizza: Pizza,
  wheat: Wheat,
  milk: Milk,
  coffee: Coffee,
  "cup-soda": CupSoda,
  wine: Wine,
  beer: Beer,
  martini: Martini,
  "glass-water": GlassWater,
  droplet: Droplet,
  droplets: Droplets,
  refrigerator: Refrigerator,
  microwave: Microwave,
  nut: Nut,
  bean: Bean,
  // Hygiene & sanitation
  bath: Bath,
  "shower-head": ShowerHead,
  toilet: Toilet,
  "spray-can": SprayCan,
  trash: Trash,
  "trash-2": Trash2,
  "brush-cleaning": BrushCleaning,
  hand: Hand,
  waves: Waves,
  wind: Wind,
  // Clothing & belongings
  shirt: Shirt,
  footprints: Footprints,
  backpack: Backpack,
  luggage: Luggage,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  glasses: Glasses,
  umbrella: Umbrella,
  watch: Watch,
  gem: Gem,
  scissors: Scissors,
  // Shelter & housing
  tent: Tent,
  "tent-tree": TentTree,
  house: House,
  "house-plug": HousePlug,
  bed: Bed,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  building: Building,
  "building-2": Building2,
  warehouse: Warehouse,
  hotel: Hotel,
  "door-open": DoorOpen,
  "door-closed": DoorClosed,
  key: Key,
  "key-round": KeyRound,
  lamp: Lamp,
  sofa: Sofa,
  armchair: Armchair,
  blinds: Blinds,
  fence: Fence,
  castle: Castle,
  landmark: Landmark,
  // Energy & weather
  flame: Flame,
  thermometer: Thermometer,
  "thermometer-sun": ThermometerSun,
  "thermometer-snowflake": ThermometerSnowflake,
  snowflake: Snowflake,
  sun: Sun,
  "sun-medium": SunMedium,
  moon: Moon,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cloud-sun": CloudSun,
  zap: Zap,
  plug: Plug,
  "plug-zap": PlugZap,
  battery: Battery,
  "battery-charging": BatteryCharging,
  lightbulb: Lightbulb,
  fan: Fan,
  // Health & medical
  heart: Heart,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  cross: Cross,
  bandage: Bandage,
  ambulance: Ambulance,
  activity: Activity,
  brain: Brain,
  ear: Ear,
  eye: Eye,
  bone: Bone,
  dna: Dna,
  microscope: Microscope,
  hospital: Hospital,
  accessibility: Accessibility,
  "hand-heart": HandHeart,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  // Legal & documents
  scale: Scale,
  gavel: Gavel,
  file: File,
  "file-text": FileText,
  files: Files,
  "file-check": FileCheck,
  "file-lock": FileLock,
  folder: Folder,
  "folder-open": FolderOpen,
  stamp: Stamp,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  book: Book,
  "book-open": BookOpen,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  pen: Pen,
  pencil: Pencil,
  signature: Signature,
  "id-card": IdCard,
  fingerprint: Fingerprint,
  scroll: Scroll,
  receipt: Receipt,
  "badge-check": BadgeCheck,
  // Information & orientation
  info: Info,
  "circle-help": CircleHelp,
  megaphone: Megaphone,
  bell: Bell,
  map: Map,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  compass: Compass,
  signpost: Signpost,
  "signpost-big": SignpostBig,
  flag: Flag,
  list: List,
  newspaper: Newspaper,
  presentation: Presentation,
  // Communication & tech
  phone: Phone,
  "phone-call": PhoneCall,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  monitor: Monitor,
  wifi: Wifi,
  "wifi-off": WifiOff,
  globe: Globe,
  "globe-2": Globe2,
  mail: Mail,
  "mail-open": MailOpen,
  send: Send,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  "at-sign": AtSign,
  rss: Rss,
  radio: Radio,
  headphones: Headphones,
  mic: Mic,
  video: Video,
  camera: Camera,
  printer: Printer,
  usb: Usb,
  bluetooth: Bluetooth,
  "qr-code": QrCode,
  scan: Scan,
  router: Router,
  "satellite-dish": SatelliteDish,
  signal: Signal,
  antenna: Antenna,
  // Transport & mobility
  bus: Bus,
  "bus-front": BusFront,
  car: Car,
  "car-front": CarFront,
  bike: Bike,
  "train-front": TrainFront,
  "tram-front": TramFront,
  plane: Plane,
  ship: Ship,
  truck: Truck,
  fuel: Fuel,
  navigation: Navigation,
  route: Route,
  milestone: Milestone,
  caravan: Caravan,
  sailboat: Sailboat,
  anchor: Anchor,
  // Money & aid
  coins: Coins,
  banknote: Banknote,
  wallet: Wallet,
  "credit-card": CreditCard,
  "hand-coins": HandCoins,
  gift: Gift,
  "piggy-bank": PiggyBank,
  euro: Euro,
  "dollar-sign": DollarSign,
  calculator: Calculator,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  "hand-helping": HandHelping,
  // Education & language
  "graduation-cap": GraduationCap,
  "book-marked": BookMarked,
  library: Library,
  languages: Languages,
  "pen-tool": PenTool,
  ruler: Ruler,
  school: School,
  blocks: Blocks,
  puzzle: Puzzle,
  // Work & tools
  briefcase: Briefcase,
  hammer: Hammer,
  wrench: Wrench,
  "hard-hat": HardHat,
  drill: Drill,
  shovel: Shovel,
  paintbrush: Paintbrush,
  construction: Construction,
  factory: Factory,
  forklift: Forklift,
  tractor: Tractor,
  axe: Axe,
  cog: Cog,
  settings: Settings,
  // People & family
  users: Users,
  "users-round": UsersRound,
  user: User,
  "user-round": UserRound,
  "user-plus": UserPlus,
  venus: Venus,
  mars: Mars,
  "venus-and-mars": VenusAndMars,
  "person-standing": PersonStanding,
  baby: Baby,
  // Community & activities
  "party-popper": PartyPopper,
  sparkles: Sparkles,
  music: Music,
  "music-2": Music2,
  guitar: Guitar,
  drama: Drama,
  palette: Palette,
  "gamepad-2": Gamepad2,
  "dice-5": Dice5,
  trophy: Trophy,
  medal: Medal,
  dumbbell: Dumbbell,
  film: Film,
  clapperboard: Clapperboard,
  piano: Piano,
  // Safety & security
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  unlock: Unlock,
  siren: Siren,
  "triangle-alert": TriangleAlert,
  "octagon-alert": OctagonAlert,
  "circle-alert": CircleAlert,
  cctv: Cctv,
  "eye-off": EyeOff,
  "fire-extinguisher": FireExtinguisher,
  "life-buoy": LifeBuoy,
  ban: Ban,
  flashlight: Flashlight,
  // Time & scheduling
  clock: Clock,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "calendar-clock": CalendarClock,
  hourglass: Hourglass,
  timer: Timer,
  "alarm-clock": AlarmClock,
  history: History,
  // Nature & animals
  "tree-pine": TreePine,
  "tree-deciduous": TreeDeciduous,
  trees: Trees,
  leaf: Leaf,
  sprout: Sprout,
  flower: Flower,
  "flower-2": Flower2,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  "paw-print": PawPrint,
  rabbit: Rabbit,
  turtle: Turtle,
  bug: Bug,
  feather: Feather,
  // Religion & culture
  church: Church,
  star: Star,
  "moon-star": MoonStar,
};

/**
 * Codes seeded before icon codes matched Lucide names. Kept out of the picker
 * so new rows use the canonical Lucide name, but resolved on render so
 * existing rows keep their glyph.
 */
const legacyIconAliases: Record<string, LucideIcon> = {
  shower: Bath,
  help: CircleHelp,
  home: House,
};

/** Selectable icon vocabulary — the canonical Lucide names, in theme order. */
export const taxonomyIconNames = Object.keys(taxonomyIcons);

export function TaxonomyIcon({
  name,
  size = 18,
  className,
}: {
  name?: string | null;
  size?: number;
  className?: string;
}) {
  const Glyph = name
    ? (taxonomyIcons[name] ?? legacyIconAliases[name] ?? CircleHelp)
    : CircleHelp;
  return (
    <Glyph size={size} strokeWidth={1.8} className={className} aria-hidden />
  );
}
